package baza_date_barci;

public enum ViewState {

	
	MENIU_INTEROGARI,
	INTEROGARE3,
	INTEROGARE4,
	INTEROGARE5,
	INTEROGARE6,
	INTEROGARE3_SUBP_A,
	INTEROGARE3_SUBP_B,
	INTEROGARE4_SUBP_A,
	INTEROGARE4_SUBP_B,
	INTEROGARE5_SUBP_A,
	INTEROGARE5_SUBP_B,
	INTEROGARE6_SUBP_A,
	INTEROGARE6_SUBP_B,
	RESULTS;
}
